# Generated by Django 5.0.6 on 2024-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Дата создания привычки'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.TimeField(default='12:00:00', verbose_name='Время выполнения привычки'),
        ),
    ]
