# Generated by Django 5.0.6 on 2024-05-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habits_data_alter_habits_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='date_send_message',
            field=models.DateField(auto_now=True, verbose_name='Дата отправки сообщения'),
        ),
    ]
